/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VaraArbetenRouteImport } from './routes/vara-arbeten'
import { Route as TjansterRouteImport } from './routes/tjanster'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as IndexRouteImport } from './routes/index'

const VaraArbetenRoute = VaraArbetenRouteImport.update({
  id: '/vara-arbeten',
  path: '/vara-arbeten',
  getParentRoute: () => rootRouteImport,
} as any)
const TjansterRoute = TjansterRouteImport.update({
  id: '/tjanster',
  path: '/tjanster',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/tjanster': typeof TjansterRoute
  '/vara-arbeten': typeof VaraArbetenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/tjanster': typeof TjansterRoute
  '/vara-arbeten': typeof VaraArbetenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/tjanster': typeof TjansterRoute
  '/vara-arbeten': typeof VaraArbetenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/kontakt' | '/tjanster' | '/vara-arbeten'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kontakt' | '/tjanster' | '/vara-arbeten'
  id: '__root__' | '/' | '/kontakt' | '/tjanster' | '/vara-arbeten'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KontaktRoute: typeof KontaktRoute
  TjansterRoute: typeof TjansterRoute
  VaraArbetenRoute: typeof VaraArbetenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vara-arbeten': {
      id: '/vara-arbeten'
      path: '/vara-arbeten'
      fullPath: '/vara-arbeten'
      preLoaderRoute: typeof VaraArbetenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tjanster': {
      id: '/tjanster'
      path: '/tjanster'
      fullPath: '/tjanster'
      preLoaderRoute: typeof TjansterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KontaktRoute: KontaktRoute,
  TjansterRoute: TjansterRoute,
  VaraArbetenRoute: VaraArbetenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
